# src/main/resources/application.yml
gmail:
  application:
    name: Gmail Demo Project
  credentials:
    path: credentials.json
  tokens:
    directory: tokens
  auth:
    port: 8887
  labels:
    definitions:
      - name: work
        color: "#42d692" # green
      - name: linkedin
        color: "#b6cff5" # light blue
      - name: slack
        color: "#fbe983" # yellow
      - name: to_trash
        color: "#e7e7e7" # grey
  processing: # NEW SECTION FOR EMAIL PROCESSING SETTINGS
    query: "is:unread" # Query to fetch emails. Example: "is:unread"
    sender-label-mapping: # Maps sender emails to specific labels
      "@ua.jooble.org": "work"
      "@linkedin.com": "linkedin"
      "@slack.com": "slack"
    process-attachments: false
    max-results: 100 # Maximum number of messages to fetch per API call (for pagination)





